# First stage
FROM alpine as builder
COPY wattivahti-logger-x86_64-unknown-linux-musl /wattivahti-logger-x86_64-unknown-linux-musl
COPY wattivahti-logger-aarch64-unknown-linux-musl /wattivahti-logger-aarch64-unknown-linux-musl
ARG TARGETARCH

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then export BINARY_PATH=wattivahti-logger-x86_64-unknown-linux-musl; elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then export BINARY_PATH=wattivahti-logger-aarch64-unknown-linux-musl; else export BINARY_PATH=wattivahti-logger-x86_64-unknown-linux-musl; fi \
    && mv ./${BINARY_PATH} ./wattivahti-logger

# Add executable permissions
RUN chmod +x ./wattivahti-logger

# Second stage: create the final image
FROM scratch
COPY --from=builder /wattivahti-logger /wattivahti-logger

USER 1000
CMD ["./wattivahti-logger"]
