contracts:
  - start_time: "2013-09-01T00:00:00"
    end_time: "2013-12-31T23:59:59"
    contract_type: "fixed"
    energy:
      basic_fee: 2.50
      day_fee: 1.23
      night_fee: 0.23
    transfer:
      basic_fee: 12.50
      day_fee: 2.34
      night_fee: 1.34
      tax_fee: 2.11172
  - start_time: "2014-01-01T00:00:00"
    end_time: "2014-06-26T23:59:59"
    contract_type: "fixed"
    energy:
      basic_fee: 4.50
      day_fee: 2.23
      night_fee: 1.23
    transfer:
      basic_fee: 13.50
      day_fee: 3.34
      night_fee: 2.34
      tax_fee: 2.35972
  - start_time: "2014-06-27T00:00:00"
    end_time: "2014-09-30T23:59:59"
    contract_type: "fixed"
    energy:
      basic_fee: 5.50
      day_fee: 3.23
      night_fee: 2.23
    transfer:
      basic_fee: 14.50
      day_fee: 4.34
      night_fee: 3.34
      tax_fee: 2.35972
  - start_time: "2014-10-01T00:00:00"
    contract_type: "spot"
    energy:
      basic_fee: 5.50
      margin: 0.25
    transfer:
      basic_fee: 14.50
      day_fee: 4.34
      night_fee: 3.34
      tax_fee: 2.35972
