spot_data_vat_multiplier:
  - start_time: "2000-01-01T00:00:00"
    end_time: "2022-11-30T23:59:59"
    value: 1.24
  - start_time: "2022-12-01T00:00:00"
    end_time: "2023-04-30T23:59:59"
    value: 1.10
  - start_time: "2023-05-01T00:00:00"
    value: 1.24

production_transfer_fees:
  - start_time: "2020-01-01T00:00:00"
    end_time: "2020-06-01T23:59:59"
    value: 1.00
  - start_time: "2020-06-02T00:00:00"
    end_time: "2021-01-01T23:59:59"
    value: 1.20
  - start_time: "2021-01-02T00:00:00"
    end_time: "2222-01-01T23:59:59"
    value: 0.09
  - start_time: "2222-01-02T00:00:00"
    value: 99.99

consumption_transfer_basic_fee:
  - start_time: "2000-01-01T00:00:00"
    end_time: "2022-10-31T23:59:59"
    value: 13.00
  - start_time: "2022-11-01T00:00:00"
    end_time: "2022-12-31T23:59:59"
    value: 23.00
  - start_time: "2023-01-01T00:00:00"
    value: 33.00

consumption_basic_fee:
  - start_time: "2000-01-01T00:00:00"
    end_time: "2022-11-30T23:59:59"
    value: 4.90
  - start_time: "2022-12-01T00:00:00"
    end_time: "2023-04-30T23:59:59"
    value: 4.35
  - start_time: "2023-05-01T00:00:00"
    value: 4.90

consumption_tax_fee:
  - start_time: "2000-01-01T00:00:00"
    value: 2.79372

consumption_transfer_fee:
  - start_time: "2021-01-02T00:00:00"
    end_time: "2222-01-01T23:59:59"
    time_or_seasonal: true
    time_config:
      start_hour: 22
      end_hour: 7
      night_fee: 1.80
      day_fee: 1.95
    seasonal_config: # Unnecessary in this scenario since time_or_seasonal is set to true
      fee: 3.00

consumption_energy_fee:
  - start_time: "2000-01-01T00:00:00"
    end_time: "2022-12-31T23:59:59"
    stock_exchange_or_fixed: false
    fixed_config:
      fee: 5.00
  - start_time: "2023-01-01T00:00:00"
    end_time: "2023-01-27T23:59:59"
    stock_exchange_or_fixed: false
    fixed_config:
      fee: 40.00
  - start_time: "2023-01-28T00:00:00"
    end_time: "2023-04-30T23:59:59"
    stock_exchange_or_fixed: true
    stock_exchange_config:
      margin: 0.22
      tax_multiplier: 1.10
  - start_time: "2023-05-01T00:00:00"
    stock_exchange_or_fixed: true
    stock_exchange_config:
      margin: 0.22
      tax_multiplier: 1.24
