name: Build and push

on:
  workflow_dispatch:
    inputs:
      version_level:
        type: choice
        required: true
        description: Version level
        options:
          - commit
          - patch
          - minor
          - major
        default: 'patch'
      specific-version:
        description: 'Specific version'
        required: false
        default: ''
      push:
        description: 'Push to DockerHub'
        required: true
        default: true
        type: boolean

jobs:
  buildVariables:
    name: "Get variables"
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.set_outputs.outputs.TAG_VERSION }}
      release_version: ${{ steps.set_outputs.outputs.RELEASE_VERSION }}
      commit_branch: ${{ steps.set_outputs.outputs.COMMIT_BRANCH }}
      commit_hash: ${{ steps.set_outputs.outputs.COMMIT_HASH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          fallback: 0.0.0

      - name: 'Get next version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Print WyriHaximus current and next version
        run: |
          echo "Major version: ${{ steps.semvers.outputs.major }}"
          echo "Minor version: ${{ steps.semvers.outputs.minor }}"
          echo "Patch version: ${{ steps.semvers.outputs.patch }}"

      - name: Get Branch
        id: branch
        run: echo "COMMIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get Hash
        id: hash
        run: echo "COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Check Branch
        run: echo "${{ env.COMMIT_BRANCH }}"

      - name: Check Hash
        run: echo "${{ env.COMMIT_HASH }}"

      - name: Set release version
        run: |
          if ${{ github.event.inputs.specific-version != '' }};
          then
            echo "TAG_VERSION=${{ github.event.inputs.specific-version }}" >> $GITHUB_ENV
            echo "RELEASE_VERSION=${{ github.event.inputs.specific-version }}" >> $GITHUB_ENV
          else
            if ${{ github.event.inputs.version_level == 'major' }};
            then
              echo "TAG_VERSION=${{ steps.semvers.outputs.major }}" >> $GITHUB_ENV
              echo "RELEASE_VERSION=${{ steps.semvers.outputs.major }}" >> $GITHUB_ENV
            elif ${{ github.event.inputs.version_level == 'minor' }};
            then
              echo "TAG_VERSION=${{ steps.semvers.outputs.minor }}" >> $GITHUB_ENV
              echo "RELEASE_VERSION=${{ steps.semvers.outputs.minor }}" >> $GITHUB_ENV
            elif ${{ github.event.inputs.version_level == 'patch' }};
            then
              echo "TAG_VERSION=${{ steps.semvers.outputs.patch }}" >> $GITHUB_ENV
              echo "RELEASE_VERSION=${{ steps.semvers.outputs.patch }}" >> $GITHUB_ENV
            else
              echo "TAG_VERSION=${{ steps.semvers.outputs.patch }}-${{ env.COMMIT_HASH }}" >> $GITHUB_ENV
              echo "RELEASE_VERSION=${{ steps.semvers.outputs.patch }}-${{ env.COMMIT_HASH }}" >> $GITHUB_ENV
            fi
          fi

      - name: Print release and tag version
        run: |
          echo "Tag version: ${{ env.TAG_VERSION }}"
          echo "Release version: ${{ env.RELEASE_VERSION }}"

      - name: Set output variables
        id: set_outputs
        run: |
          echo "TAG_VERSION=${{ env.TAG_VERSION }}" >> $GITHUB_OUTPUT
          echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}" >> $GITHUB_OUTPUT
          echo "COMMIT_BRANCH=${{ env.COMMIT_BRANCH }}" >> $GITHUB_OUTPUT
          echo "COMMIT_HASH=${{ env.COMMIT_HASH }}" >> $GITHUB_OUTPUT

  x86:
    name: "Build and push x86 wattivahti-logger"
    needs: [buildVariables]
    runs-on: ubuntu-latest
    env:
      TAG_VERSION: ${{ needs.buildVariables.outputs.tag_version }}
      RELEASE_VERSION: ${{ needs.buildVariables.outputs.release_version }}
      COMMIT_BRANCH: ${{ needs.buildVariables.outputs.commit_branch }}
      COMMIT_HASH: ${{ needs.buildVariables.outputs.commit_hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: x86_build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:amd64-${{ env.RELEASE_VERSION }},${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:amd64-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  arm64:
    name: "Build and push arm64 wattivahti-logger"
    needs: [buildVariables]
    runs-on: self-hosted-arm64
    env:
      TAG_VERSION: ${{ needs.buildVariables.outputs.tag_version }}
      RELEASE_VERSION: ${{ needs.buildVariables.outputs.release_version }}
      COMMIT_BRANCH: ${{ needs.buildVariables.outputs.commit_branch }}
      COMMIT_HASH: ${{ needs.buildVariables.outputs.commit_hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: arm64_build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          file: ./Dockerfile.arm64
          push: ${{ inputs.push }}
          tags: ${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:arm64-${{ env.RELEASE_VERSION }},${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:arm64-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  auth:
    name: "Build and push wattivahti-auth"
    needs: [buildVariables]
    runs-on: ubuntu-latest
    env:
      TAG_VERSION: ${{ needs.buildVariables.outputs.tag_version }}
      RELEASE_VERSION: ${{ needs.buildVariables.outputs.release_version }}
      COMMIT_BRANCH: ${{ needs.buildVariables.outputs.commit_branch }}
      COMMIT_HASH: ${{ needs.buildVariables.outputs.commit_hash }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: auth_build
        uses: docker/build-push-action@v4
        with:
          context: ./node_auth
          platforms: linux/amd64,linux/arm64
          file: ./node_auth/Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ secrets.DOCKER_USERNAME }}/wattivahti-auth:${{ env.RELEASE_VERSION }},${{ secrets.DOCKER_USERNAME }}/wattivahti-auth:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  multiarch_logger:
    needs: [x86, arm64]
    name: Create a new multiarch tag for logger
    runs-on: ubuntu-latest
    steps:
      - name: Create and push manifest images for version
        uses: Noelware/docker-manifest-action@0.4.0
        with:
            inputs: ${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:${{ env.RELEASE_VERSION }}
            images: ${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:amd64-${{ env.RELEASE_VERSION }},${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:arm64-${{ env.RELEASE_VERSION }}
            push: true
      - name: Create and push manifest images for latest
        uses: Noelware/docker-manifest-action@0.4.0
        with:
            inputs: ${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:latest
            images: ${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:amd64-latest,${{ secrets.DOCKER_USERNAME }}/wattivahti-logger:arm64-latest
            push: true

  create_release:
    needs: [buildVariables, x86, arm64, auth]
    name: Create a new release
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.version_level != 'commit' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          TAG_VERSION: ${{ needs.buildVariables.outputs.tag_version }}
          RELEASE_VERSION: ${{ needs.buildVariables.outputs.release_version }}
          COMMIT_BRANCH: ${{ needs.buildVariables.outputs.commit_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag: "${{ env.TAG_VERSION }}"
          name: "${{ env.RELEASE_VERSION }}"
          commit: "${{ env.COMMIT_BRANCH }}"
          draft: false
          prerelease: false
          allowUpdates: true
          updateOnlyUnreleased: true
